- hosts: local
  connection: local
  become: yes
  tasks:

  - name: Container is running
    docker:
      name=gobuildtest
      image=gobuild
      volumes=/home/jenkins/goapp/code:/go/src/helloapp
      volumes=/home/jenkins/goapp/deploy:/tmp/deploy
      entrypoint=sh buildgo.sh

  - name: stop runing docker compose
    command: docker-compose stop

  - name: remove docker compose
    command: docker-compose rm -f

  - name: remove docker compose
    command: docker-compose up
