- hosts: local
  connection: local
  become: yes
  tasks:

  - name: Stop and Remove contianers using docker-compose
    shell: /usr/local/bin/docker-compose stop && /usr/local/bin/docker-compose rm -f

  - name: Build image for gobuild
    shell: cd /opt/gitrepo/goapp/build/ && docker build -t gobuild .

  - name: Build helloapp
    shell: docker run --rm -v $PWD/code:/go/src/helloapp -v $PWD/deploy:/tmp/deploy gobuild sh /tmp/buildgo.sh

  - name: Build image for gonginx 
    shell: cd /opt/gitrepo/goapp/nginx/ && docker build -t gonginx .

  - name: Build image for godeploy
    shell: cd /opt/gitrepo/goapp/deploy/ && docker build -t godeploy .

  - name: Build contianers using docker-compose
    shell: /usr/local/bin/docker-compose up -d

