node1:
    image: godeploy
    volumes:
      - $PWD/deploy/helloapp:/go/bin/helloapp
    ports:
      - "8484"

node2:
    image: godeploy
    volumes:
      - $PWD/deploy/helloapp:/go/bin/helloapp
    ports:
      - "8484"

nginxserver:
    image: gonginx
    command: nginx -g 'daemon off;'
    links:
      - node1:node1
      - node2:node2
    ports:
      - "80:80"
    stdin_open: true
    tty: true
