nginx:
    image: gonginx
    container_name: nginx
    links:
      - node1:node1
      - node2:node2
    ports:
      - "80:80"
node1:
    image: godeploy
    container_name: node1
    volumes:
      - deploy/helloapp:/go/bin/helloapp
    ports:
      - "8484"
node2:
    image: godeploy
    container_name: node2
    volumes:
      - deploy/helloapp:/go/bin/helloapp
    ports:
      - "8484"
