node1:
    image: godeploy
    volumes:
      - /home/jenkins/goapp/deploy/helloapp:/go/bin/helloapp
    ports:
      - "8484"

node2:
    image: godeploy
    volumes:
      - /home/jenkins/goapp/deploy/helloapp:/go/bin/helloapp
    ports:
      - "8484"

nginxserver:
    image: gonginx
    links:
      - node1:node1
      - node2:node2
    ports:
      - "80:80"
